package controllers

import (
	"errors"
	"net/http"
	cfg "visit-sidayu-backend/internal/config"
	myE "visit-sidayu-backend/internal/constants/errorss"
	hp "visit-sidayu-backend/internal/helpers"
	"visit-sidayu-backend/internal/helpers/validation"
	"visit-sidayu-backend/internal/models"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

var (
	pluralTml   = "timelines"
	singularTml = "timeline"
)

func GetAllTimelines(ctx *gin.Context) {
	var timelines []models.Timelines
	query := cfg.DB.Preload("TimelineData").Model(&models.Timelines{})
	search := ctx.Query("search")
	if search != "" {
		query = query.Where("name ILIKE ?", "%"+search+"%")
	}

	// add filters by blog_id and culture_blog_id
	blogId := ctx.Query("blog_id")
	if blogId != "" {
		query = query.Where("blog_id = ?", blogId)
	}

	cultureBlogId := ctx.Query("culture_blog_id")
	if cultureBlogId != "" {
		query = query.Where("culture_blog_id = ?", cultureBlogId)
	}

	meta, offset := hp.CalcMeta(ctx, query)
	err := query.Offset(offset).Limit(meta.Limit).Find(&timelines).Error
	if err != nil {
		return
	}

	if len(timelines) == 0 {
		hp.RespError(ctx, http.StatusNotFound, pluralTml+myE.Msg404Err, nil, myE.Err404Fill)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, pluralTml+myE.MsgGet200, timelines, "", meta)
}

func GetTimelineByID(ctx *gin.Context) {
	id, err := validation.ParseUrlID(ctx)
	if err != nil {
		return
	}

	var timeline models.Timelines
	err = cfg.DB.Preload("TimelineData").First(&timeline, "id = ?", id).Error
	if err != nil {
		hp.RespError(ctx, http.StatusNotFound, singularTml+myE.Msg404Err, nil, myE.Err404Fill)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, singularTml+myE.MsgGet200, timeline, "", nil)
}

// timeline are created by other models, but i'll keep it here just in case I need it
// func CreateTimeline(ctx *gin.Context) {

// }

// this code is generated by chat-gpt
func UpdateTimeline(ctx *gin.Context) {
	_, err := validation.AuthUser(ctx)
	if err != nil {
		return
	}

	id, err := validation.ParseUrlID(ctx)
	if err != nil {
		return
	}

	input, err := validation.ParseInputJSON[models.UpdateTimelines](ctx)
	if err != nil {
		return
	}

	var timeline models.Timelines
	err = cfg.DB.Preload("TimelineData").First(&timeline, "id = ?", id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			hp.RespError(ctx, http.StatusNotFound, singularTml+myE.Msg404Err, nil)
			return
		}

		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	tx := cfg.DB.Begin()

	// =====================
	// Update parent
	// =====================

	if input.Name != nil {
		timeline.Name = *input.Name
	}

	if input.Description != nil {
		timeline.Description = *input.Description
	}

	if err := tx.Save(&timeline).Error; err != nil {
		tx.Rollback()
		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	// =====================
	// Update/Create children
	// =====================

	existing := make(map[uuid.UUID]models.TimelinesElement)

	for _, item := range timeline.TimelineData {
		existing[item.ID] = item
	}

	for _, req := range input.TimelineData {

		// -----------------
		// CREATE
		// -----------------

		if req.ID == nil {

			newItem := models.TimelinesElement{
				Name:             req.Name,
				TimelineDatetime: req.TimelineDatetime,
				Description:      req.Description,
				ExternalLink:     req.ExternalLink,
				TimelinesID:      timeline.ID,
			}

			if err := tx.Create(&newItem).Error; err != nil {
				tx.Rollback()
				hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
				return
			}

			continue
		}

		// -----------------
		// UPDATE
		// -----------------

		old, ok := existing[*req.ID]
		if !ok {
			tx.Rollback()
			hp.RespError(ctx, http.StatusBadRequest, "timeline element not found", nil)
			return
		}

		old.Name = req.Name
		old.TimelineDatetime = req.TimelineDatetime
		old.Description = req.Description
		old.ExternalLink = req.ExternalLink

		if err := tx.Save(&old).Error; err != nil {
			tx.Rollback()
			hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
			return
		}
	}

	tx.Commit()

	cfg.DB.Preload("TimelineData").First(&timeline, timeline.ID)

	hp.RespSuccess(ctx, http.StatusOK, singularTml+myE.MsgPtc200, timeline, "", nil)
}

func DeleteTimeline(ctx *gin.Context) {
	_, err := validation.AuthUser(ctx)
	if err != nil {
		return
	}

	id, err := validation.ParseUrlID(ctx)
	if err != nil {
		return
	}

	var timeline models.Timelines
	err = cfg.DB.Preload("TimelineData").First(&timeline, "id = ?", id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			hp.RespError(ctx, http.StatusNotFound, singularTml+myE.Msg404Err, err)
			return
		}

		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	err = cfg.DB.Unscoped().Delete(&timeline).Error
	if err != nil {
		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, singularTml+myE.MsgDel200, timeline, "", nil)
}
