package controllers

import (
	"errors"
	"net/http"
	cfg "visit-sidayu-backend/internal/config"
	myE "visit-sidayu-backend/internal/constants/errorss"
	hp "visit-sidayu-backend/internal/helpers"
	"visit-sidayu-backend/internal/helpers/validation"
	"visit-sidayu-backend/internal/models"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

var (
	pluralTml   = "timelines"
	singularTml = "timeline"
)

func GetAllTimelines(ctx *gin.Context) {
	var timelines []models.Timelines
	query := cfg.DB.Preload("TimelineData", func(db *gorm.DB) *gorm.DB {
		return db.Order("timeline_datetime ASC")
	}).Model(&models.Timelines{})
	search := ctx.Query("search")
	if search != "" {
		query = query.Where("name ILIKE ?", "%"+search+"%")
	}

	// add filters by blog_id and culture_blog_id
	blogId := ctx.Query("blog_id")
	if blogId != "" {
		query = query.Where("blog_id = ?", blogId)
	}

	cultureBlogId := ctx.Query("culture_blog_id")
	if cultureBlogId != "" {
		query = query.Where("culture_blog_id = ?", cultureBlogId)
	}

	meta, offset := hp.CalcMeta(ctx, query)
	err := query.Offset(offset).Limit(meta.Limit).Find(&timelines).Error
	if err != nil {
		return
	}

	if len(timelines) == 0 {
		hp.RespError(ctx, http.StatusNotFound, pluralTml+myE.Msg404Err, nil, myE.Err404Fill)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, pluralTml+myE.MsgGet200, timelines, "", meta)
}

func GetTimelineByID(ctx *gin.Context) {
	id, err := validation.ParseUrlID(ctx)
	if err != nil {
		return
	}

	var timeline models.Timelines
	err = cfg.DB.Preload("TimelineData", func(db *gorm.DB) *gorm.DB {
		return db.Order("timeline_datetime ASC")
	}).First(&timeline, "id = ?", id).Error
	if err != nil {
		hp.RespError(ctx, http.StatusNotFound, singularTml+myE.Msg404Err, nil, myE.Err404Fill)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, singularTml+myE.MsgGet200, timeline, "", nil)
}

// timeline are created by other models, but i'll keep it here just in case I need it
// func CreateTimeline(ctx *gin.Context) {

// }

// this code is generated by Gemini 3.1 Pro
func UpdateTimeline(ctx *gin.Context) {
	// =====================
	// 1. Authorization & Parse
	// =====================
	_, err := validation.AuthUser(ctx)
	if err != nil {
		return
	}

	id, err := validation.ParseUrlID(ctx)
	if err != nil {
		return
	}

	input, err := validation.ParseInputJSON[models.UpdateTimelines](ctx)
	if err != nil {
		return
	}

	// =====================
	// 2. Get Existing Timeline
	// =====================
	var timeline models.Timelines
	err = cfg.DB.Preload("TimelineData").First(&timeline, "id = ?", id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			hp.RespError(ctx, http.StatusNotFound, singularTml+myE.Msg404Err, nil)
			return
		}
		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	// =====================
	// 3. Begin Transaction
	// =====================
	tx := cfg.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// =====================
	// 4. Update Parent
	// =====================
	parentUpdates := map[string]any{}
	if input.Name != nil {
		parentUpdates["name"] = *input.Name
	}
	if input.Description != nil {
		parentUpdates["description"] = *input.Description
	}

	if len(parentUpdates) > 0 {
		// PENTING: Gunakan model kosong dan `.Where` agar GORM tidak mencoba
		// menyentuh/meng-update relasi (TimelineData) yang sudah di-preload secara otomatis.
		if err := tx.Model(&models.Timelines{}).Where("id = ?", id).Updates(parentUpdates).Error; err != nil {
			tx.Rollback()
			hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
			return
		}
	}

	// =====================
	// 5. Mapping Existing Child
	// =====================
	existing := make(map[uuid.UUID]models.TimelinesElement)
	for _, item := range timeline.TimelineData {
		existing[item.ID] = item
	}

	// Menyimpan ID yang masih dipertahankan dari payload
	visited := make(map[uuid.UUID]bool)

	// =====================
	// 6. Proses Payload (Create & Update Child)
	// =====================
	for _, req := range input.TimelineData {

		// ---------- CREATE (Jika tidak bawa ID) ----------
		if req.ID == nil || *req.ID == uuid.Nil {
			newItem := models.TimelinesElement{
				Name:             req.Name,
				TimelineDatetime: req.TimelineDatetime,
				Description:      req.Description,
				ExternalLink:     req.ExternalLink,
				TimelinesID:      id, // Langsung pakai 'id' parent dari URL
			}

			if err := tx.Create(&newItem).Error; err != nil {
				tx.Rollback()
				hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
				return
			}
			continue
		}

		// ---------- UPDATE (Jika bawa ID) ----------
		_, ok := existing[*req.ID]
		if !ok {
			tx.Rollback()
			hp.RespError(ctx, http.StatusBadRequest, "timeline element with id "+req.ID.String()+" not found", nil)
			return
		}

		// Tandai bahwa ID ini ada di payload (tidak boleh dihapus)
		visited[*req.ID] = true

		childUpdates := map[string]any{
			"name":              req.Name,
			"timeline_datetime": req.TimelineDatetime,
			"description":       req.Description,
			"external_link":     req.ExternalLink,
		}

		// Update by ID secara langsung
		if err := tx.Model(&models.TimelinesElement{}).Where("id = ?", *req.ID).Updates(childUpdates).Error; err != nil {
			tx.Rollback()
			hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
			return
		}
	}

	// =====================
	// 7. Proses Delete Child (Yang tidak ada di Payload)
	// =====================
	for _, item := range timeline.TimelineData {
		// Jika ID tidak ada di map visited, artinya user tidak mengirimkannya lagi, maka HAPUS!
		if !visited[item.ID] {
			if err := tx.Delete(&models.TimelinesElement{}, "id = ?", item.ID).Error; err != nil {
				tx.Rollback()
				hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
				return
			}
		}
	}

	// =====================
	// 8. Commit
	// =====================
	if err := tx.Commit().Error; err != nil {
		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	// =====================
	// 9. Reload Data & Return
	// Best practice: reload data after commit ensuring correct data is updated
	// =====================
	if err := cfg.DB.Preload("TimelineData", func(db *gorm.DB) *gorm.DB {
		return db.Order("timeline_datetime ASC")
	}).First(&timeline, "id = ?", id).Error; err != nil {
		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, singularTml+myE.MsgPtc200, timeline, "", nil)
}

func DeleteTimeline(ctx *gin.Context) {
	_, err := validation.AuthUser(ctx)
	if err != nil {
		return
	}

	id, err := validation.ParseUrlID(ctx)
	if err != nil {
		return
	}

	var timeline models.Timelines
	err = cfg.DB.Preload("TimelineData").First(&timeline, "id = ?", id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			hp.RespError(ctx, http.StatusNotFound, singularTml+myE.Msg404Err, err)
			return
		}

		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	err = cfg.DB.Unscoped().Delete(&timeline).Error
	if err != nil {
		hp.RespError(ctx, http.StatusInternalServerError, myE.MsgSvrErr, err)
		return
	}

	hp.RespSuccess(ctx, http.StatusOK, singularTml+myE.MsgDel200, timeline, "", nil)
}
